### ISSUE TITLE
How to specify the covalent bond between ligand and residue

### ISSUE THREAD

**Issue by nthpham** [mabr3112/riff_diff_protflow#15]
Hello,
It is not unclear for me how to specify the option covalent bond between 2 atoms. I am not sure what to specify in RotAtom
'RotAtomA:ligand_resnum1:LigAtomA,theozyme_resnum:RotAtomB:ligand_resnum2:LigAtomB'

Let's say I have a covalent bond between  atom NZ of LYS185 and atom C3 of ligand A300,
Should I put  'A300:C3,A185:NZ' ?

**Comment by TecnomaLaser** [comment]
Hi,
did you pull the newest version of the identify_fragments.py script? The description in the old one was incorrect, sorry. I hope the new explanation is a bit better now. 
The residue information has to be first, then the ligand. In your case, it would be 'A185-NZ:A300-C3' (assuming LYS185 is on chain A). Additional covalent bonds should be separated with ,
Hope that helps!
Cheers
Adrian

**Comment by nthpham** [comment]
Thank you for your help. I just pulled the newest version. It worked.
